name: Hello World Workflow

on:
  push:
    branches: [ master, main ] # Sesuaikan dengan branch utama Anda

jobs:
  greeting:
    runs-on: self-hosted
    steps:
    - name: Say Hello
      run: echo "Hello, World! ðŸ‘‹ dari WSL Debian"

    - name: Show System Info
      run: |
        echo "Hostname: $(hostname)"
        echo "Whoami: $(whoami)"
