name: Hello World Workflow

on:
  push:
    branches: [ master, main ] # Sesuaikan dengan branch utama Anda

jobs:
  greeting:
    runs-on: [self-hosted, my-laptop] # PASTIKAN label ini sama dengan Tahap 2 Langkah 4

    steps:
    - name: Say Hello
      run: echo "Hello, World! ðŸ‘‹ dari WSL Debian"

    - name: Show System Info
      run: |
        echo "Hostname: $(hostname)"
        echo "Whoami: $(whoami)"
